travis:
  secure:
    BINSTAR_TOKEN: bq1++wg1fsw2Zhn3I9AjAx8BTwE51r0PSjsuZRsUZN8kz+JxWdrjOzO+FajR8wJ4Z1+xWkGXTD1TIwRqlXwn3dS5rJWqlSyy89ZqF0/BUqDfbL3H3p5wGvv9Aruxkoddg5AseZ/cvQln5j7MAWdoVycIiUCiUR1FMw35fKCNUquWjegXynTMW6TZK2AI/J6rux/jl13Hcy4JDsdEu4RYH3mttNvzLyTz6fNxom/QHQwoP5nF1NqIspXCaAhV1RvSadGdIY0SSj+KCF35NqJDA75vAuCODzCYy4G1PnbliZAB6cRoREvfQENFYX0BlZcVQiQSyj68MtipPJX2b9qJboJ3eh3ECAiYNb4e0MbrgjXA9Hsfd3qlbsjNckiLxh9gTiJZ3PZP0mSAu4JuEISwTSu7VLb51ndrC7OkXfFvCQMwPi2ZM1uRryPfDjZhGR3tLLrTqk7JRMm1TROWetxBY7bAMWwZXrxrlyaoEAk2b7jGa6lAjqfKWHeZeO830YwO2Hyc7Z5pcHn8j2Ze/U7U/WWiYccNWvA43KRLF0gwxGbXbuvRgcMpyRdZ0eA5icjmHHgwWHkiaL1rW7OI96bX/UK02eZv1WVtHQB+m66lPvMlGRgjAKxyffkLIJJkLWULhaIqW2UDhAvmKc7yRr9lEdX+oQwaaGzkMlx4vcFd4Sw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
