travis:
  secure:
    BINSTAR_TOKEN: naTMHqWhKmfq6fYZ6/DLFRn8jj5/WTjLQpUJk8ZhmuU0A2hMm/GJ42ThQzqJR6Zonunz6DlQtDjL1F9/Xg5GT/So9c4yFiU/T1hhNHthOtqSP7je+Px0LmqwFe1SInXp9XbtF4MGFqearYf28m+UvR/A/MY4HTWGIdSlTaK3c3Y3rDn7dZY2E9PpKOWuLoU8sTR92GvWuNMrC0rD91GY2fWPooYKJxBStJr4aQGZC3sdO8Q67n57NY3DMNl0HH/D4ghNP1ehtHGIUJhRxKMylu9+zbT+z005XfGni8hWuBveA8ImNZ0wj0u+MNxsdVkgoj0B6glJjVDVLgd9KYny9Nmul/RWlWuMhjRK02pCF/sziUu96uGtrtpqFHPFYlgZ8o2lPr49XRuWf2CPKYVb9NXoWOwEYWll+RqGK8/eoG2ux0HqTkz9wUckkvIMLm9dhzxW3Z9j1xpGqVV7XsuQTCx6HzSstoDX9X2aImFqsiPusEhjSpN6G7fSt9N4deXHvmPR560N1TJViDaHy1pHerkWsuMOXkiLKxdiNQ0pv28KyFAexOCiGPjZdKHb6xPuXAHVBguSb4+jwCgl8bK/uzScrB8t/3OawVraR8UWJ3+YiCUndsFwWSMq5hxoQs44YBFhs+tFLCB5NzHxC5eq1CnMKvgKysragZ3jKNmMH2A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
